# Generated by Django 4.2.4 on 2023-08-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayerApp', '0002_employees_employeename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('MusicID', models.AutoField(primary_key=True, serialize=False)),
                ('MusicName', models.CharField(max_length=100)),
            ],
        ),
    ]
