# Generated by Django 4.2.4 on 2023-08-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayerApp', '0003_music'),
        ('MusicPlayerApp', '0003_musics'),
    ]

    operations = [
    ]
