# Generated by Django 4.2.4 on 2023-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayerApp', '0004_merge_0003_music_0003_musics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.AddField(
            model_name='employees',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
